# This function takes a user query as input and returns a response generated by the OpenAI GPT-3.5-turbo model.
# It uses the OpenAI API to create a chat completion with the provided query.

def getResponse(query):
    # Import the OpenAI library to interact with the OpenAI API
    import openai

    # Set the API key for authentication; replace "<ENTER RETRIEVED OPENAI API>" with your actual API key
    openai.api_key = "<ENTER RETRIEVED OPENAI API>"

    # Create a completion using the ChatCompletion endpoint of OpenAI
    # The 'model' parameter specifies which model to use, here it's "gpt-3.5-turbo"
    # The 'messages' parameter is a list of dictionaries that simulates a conversation
    # with roles such as 'user' and their respective content.
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": query}  # The query provided by the user
        ]
    )

    # Return the generated response from the assistant
    return completion.choices[0].message['content']
    
